
name: AUS Street Graph
permissions:
  contents: write
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build street
        run: |
          curl -L https://repo1.maven.org/maven2/org/opentripplanner/otp/2.2.0/otp-2.2.0-shaded.jar -o otp.jar
          mkdir aus
          mkdir nsw
          mkdir vic
          curl -L https://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf -o aus/osm.pbf

          docker run -it -w /wkd -v $(pwd):/wkd stefda/osmium-tool osmium extract --bbox=139.77,-37.61,154.36,-27.53 -o nsw/osm.pbf aus/osm.pbf
          docker run -it -w /wkd -v $(pwd):/wkd stefda/osmium-tool osmium extract --bbox=139.77,-39.59,152.71,-33.65 -o vic/osm.pbf aus/osm.pbf

          java -Xmx7G -jar otp.jar --buildStreet nsw
          java -Xmx7G -jar otp.jar --buildStreet vic
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            nsw/streetGraph.obj
          tag_name: nsw-street-graph
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vic/streetGraph.obj
          tag_name: vic-street-graph
