name: Berlin Street Graph
permissions:
  contents: write
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build street
        run: |
          curl -L https://repo1.maven.org/maven2/org/opentripplanner/otp/2.2.0/otp-2.2.0-shaded.jar -o otp.jar
          mkdir berlin
          curl -L https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -o berlin/osm.pbf
          
          java -Xmx7G -jar otp.jar --buildStreet berlin
          mv berlin/streetGraph.obj streetGraph.obj
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            streetGraph.obj
          tag_name: berlin-street-graph
