name: Test
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      url:
        description: 'Ignore'
        required: false

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Download
        run: |
          curl -L https://repo1.maven.org/maven2/org/opentripplanner/otp/2.2.0/otp-2.2.0-shaded.jar -o otp.jar
          mkdir berlin
          curl -L https://download.geofabrik.de/europe/germany/berlin-latest.osm.pbf -o berlin/osm.pbf
          curl -L https://vbb.de/vbbgtfs -o berlin/vbb-gtfs.zip
          
          java -Xmx2G -jar otp.jar --build --serve berlin
